# Server configuration
server.port=8080

# External API endpoint
external.api.baseurl=https://jsonplaceholder.typicode.com

# Logging configuration
logging.level.ca.dhruvanshi=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG